export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSE = "FETCH_COURSE";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_COURSE_CATEGORIES = "FETCH_COURSE_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
